ResumeCoverLetterCreator/Pages/Edit/Group.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ResumeCoverLetterCreator.DataAccess;

namespace ResumeCoverLetterCreator.Pages.Edit
{
    public class GroupModel : PageModel
    {
        private readonly ResumeCreatorDbContext _resumeDbContext;

        public GroupModel(ResumeCreatorDbContext resumeDbContext)
        {
            _resumeDbContext = resumeDbContext;
        }

        public TagGroup Group { get; set; } = new TagGroup();

        public void OnGet(int id)
        {
            if(id <= 0)
            {
                throw new ArgumentException("Invalid Id");
            }
            Group = _resumeDbContext.TagGroups.Include(tg => tg.DocumentTags).Include(tg => tg.GroupOptions).FirstOrDefault(tg => tg.Id == id) ?? new TagGroup();
        }

        public IActionResult OnPostChangeName(int id, string newName)
        {
            TagGroup? groupToChange = _resumeDbContext.TagGroups.FirstOrDefault(tg => id > 0 && tg.Id == id);
            if(groupToChange is not null)
            {
                groupToChange.Name = newName;
                _resumeDbContext.SaveChanges();
            }
            
            return RedirectToPage();
        }

        public IActionResult OnPostAddTag(int groupId, string name)
        {
            if(!string.IsNullOrEmpty(name) && name.Length > 1 && name.StartsWith('$'))
            {
                var group = _resumeDbContext.TagGroups.FirstOrDefault(g => g.Id == groupId);
                if(group is not null)
                {
                    _resumeDbContext.DocumentTags.Add(new DocumentTag
                    {
                        TagGroup = group,
                        TagName = name
                    }) ;

                    _resumeDbContext.SaveChanges();
                }                   
            }
            
            return RedirectToPage();
        }

        public IActionResult OnPostDeleteTag(int id)
        {

            DocumentTag? tagToDelete = _resumeDbContext.DocumentTags.FirstOrDefault(tg => id > 0 && tg.Id == id);
            if (tagToDelete is not null)
            {
                _resumeDbContext.DocumentTags.Remove(tagToDelete);
                _resumeDbContext.SaveChanges();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostDeleteOption(int id)
        {

            GroupOptionsItem? optionToDelete = _resumeDbContext.GroupOptions.FirstOrDefault(tg => id > 0 && tg.Id == id);
            if (optionToDelete is not null)
            {
                _resumeDbContext.GroupOptions.Remove(optionToDelete);
                _resumeDbContext.SaveChanges();
            }
            return RedirectToPage();
        }
    }
}

ResumeCoverLetterCreator/Pages/Edit/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ResumeCoverLetterCreator.DataAccess;

namespace ResumeCoverLetterCreator.Pages.Edit
{
    public class IndexModel : PageModel
    {
        private readonly ResumeCreatorDbContext _resumeDbContext;

        public IndexModel(ResumeCreatorDbContext resumeDbContext)
        {
            _resumeDbContext = resumeDbContext;
        }

        public IEnumerable<TagGroup> TagGroups { get; set; } = Enumerable.Empty<TagGroup>();

        public void OnGet()
        {
            TagGroups = _resumeDbContext.TagGroups;
        }
        
        public IActionResult OnPostAddGroup(string groupName = "New Group")
        {
            _resumeDbContext.TagGroups.Add(new TagGroup { Name = groupName });
            _resumeDbContext.SaveChanges();

            return RedirectToPage();
        }

        public IActionResult OnPostDeleteGroup(int id)
        {
            TagGroup? groupToDelete = _resumeDbContext.TagGroups.FirstOrDefault(tg => id > 0 && tg.Id == id);
            if(groupToDelete is not null)
            {
                _resumeDbContext.TagGroups.Remove(groupToDelete);
                _resumeDbContext.SaveChanges();
            }

            return RedirectToPage();
        }
    }
}

ResumeCoverLetterCreator/Pages/Edit/Option.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ResumeCoverLetterCreator.DataAccess;

namespace ResumeCoverLetterCreator.Pages.Edit
{
    public class OptionModel : PageModel
    {
        private readonly ResumeCreatorDbContext _resumeContext;

        public OptionModel(ResumeCreatorDbContext resumeContext)
        {
            _resumeContext = resumeContext;
        }

        public GroupOptionsItem Option { get; set; } = new GroupOptionsItem();

        public void OnGet(int? id, int groupId)
        {
            var optionToEdit = _resumeContext.GroupOptions
                .Include(o => o.TagGroup)
                .ThenInclude(g => g.DocumentTags)
                .ThenInclude(t => t.TagContent)
                .Include(o => o.TagContent)
                .FirstOrDefault(o => id.HasValue && o.Id == id);
            
            if(optionToEdit is not null)
            {
                Option = optionToEdit;
            }
            else {
                var parentGroup = _resumeContext.TagGroups
                    .Include(g => g.DocumentTags)
                    .ThenInclude(t => t.TagContent)
                    .FirstOrDefault(g => groupId > 0 && g.Id == groupId);
                if(parentGroup is not null)
                {
                    Option = new GroupOptionsItem { TagGroup = parentGroup };
                }
            }
        }

        public IActionResult OnPostSave(int id, int groupId, string name, Dictionary<int,int> tagImplementations)
        {
            // TODO: correct validation and processing
            if (!((id > 0 || groupId > 0) && !string.IsNullOrEmpty(name)))
                return RedirectToPage();

            GroupOptionsItem? optionToAddOrEdit = null;
            // Option is a new one
            if (id <= 0 && groupId > 0)
            {
                var parentGroup = _resumeContext.TagGroups.FirstOrDefault(g => g.Id == groupId);
                if(parentGroup is not null)
                {
                    optionToAddOrEdit = new GroupOptionsItem
                    {
                        TagGroup = parentGroup,
                        Name = name
                    };

                    _resumeContext.GroupOptions.Add(optionToAddOrEdit);
                }   
            }
            // Existing
            else if (id > 0)
            {
                optionToAddOrEdit = _resumeContext.GroupOptions
                   .Include(o => o.TagContent)
                   .FirstOrDefault(o => o.Id == id);               
            }

            if(optionToAddOrEdit is not null)
            {
                var implementations = _resumeContext.TagContent.Where(c => tagImplementations.Select(i => i.Value).Contains(c.Id)).ToList();
                optionToAddOrEdit.TagContent = implementations;
                _resumeContext.SaveChanges();
            }
            return RedirectToPage();
        }
    }
}

ResumeCoverLetterCreator/Pages/Edit/Tag.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ResumeCoverLetterCreator.DataAccess;

namespace ResumeCoverLetterCreator.Pages.Edit
{
    public class TagModel : PageModel
    {
        private readonly ResumeCreatorDbContext _resumeDbContext;

        public TagModel(ResumeCreatorDbContext resumeDbContext)
        {
            _resumeDbContext = resumeDbContext;
        }

        public DocumentTag Tag { get; set; } = new DocumentTag();

        public void OnGet(int id)
        {
            if(id <= 0)
            {
                throw new ArgumentException("Id must be positive number");
            }

            Tag = _resumeDbContext.DocumentTags.Include(t => t.TagGroup).Include(t => t.TagContent).FirstOrDefault(t => id > 0 && t.Id == id) ?? new DocumentTag();
        }

        public IActionResult OnPostChangeContent(int id, string content)
        {
            var contentToChange = _resumeDbContext.TagContent.FirstOrDefault(c => c.Id == id);
            if(contentToChange is not null)
            {
                contentToChange.Content = content;
                _resumeDbContext.SaveChanges();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostChangeName(int id, string name)
        {
            DocumentTag? tagToChange = _resumeDbContext.DocumentTags.FirstOrDefault(tg => id > 0 && tg.Id == id);
            if (tagToChange is not null)
            {
                tagToChange.TagName = name;
                _resumeDbContext.SaveChanges();
            }

            return RedirectToPage();
        }

        public IActionResult OnPostDeleteContent(int id, string content)
        {
            var contentToDelete = _resumeDbContext.TagContent.FirstOrDefault(c => c.Id == id);
            if (contentToDelete is not null)
            {
                _resumeDbContext.TagContent.Remove(contentToDelete);
                _resumeDbContext.SaveChanges();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostAddContent(int tagId, string content)
        {
            var contentTag = _resumeDbContext.DocumentTags.FirstOrDefault(t => t.Id == tagId);
            if(contentTag is not null)
            {
                _resumeDbContext.TagContent.Add(new TagContentItem
                {   
                    DocumentTag = contentTag,
                    Content = content
                });

                _resumeDbContext.SaveChanges();
            }

            return RedirectToPage();

        }
    }
}

ResumeCoverLetterCreator/Pages/Edit/Group.cshtml
@page "{id:int}"
@model ResumeCoverLetterCreator.Pages.Edit.GroupModel
@{
    ViewBag.Title = "Edit Group";
}
<h1>Group</h1>
<form  asp-page-handler="ChangeName" method="post">
    <input type="hidden" name="id" value="@Model.Group.Id"/>
    <label>Name:</label>
    <input type="text" name="newName" value="@Model.Group.Name"/>
    <input class="btn btn-primary" type="submit" value="Save"/>
</form>

<h3>Tags</h3>
<table>
    @foreach(var tag in Model.Group.DocumentTags)
    {
        <tr>
            <td>@tag.TagName</td>
            <td><a class="btn btn-secondary" asp-page="/Edit/Tag" asp-route-id="@tag.Id">Edit</a></td>
            <td>
                <form asp-page-handler="DeleteTag" method="post">
                    <input type="hidden" name="id" value="@tag.Id" />
                    <button class="btn btn-secondary" onclick="return confirm('Are you sure want to delete tag @tag.TagName?')">Delete</button>
                </form>
            </td>       
        </tr>
    }
</table>
<form asp-page-handler="AddTag" method="post">
    <input type="hidden" name="groupId" value="@Model.Group.Id"/>
    <input type="text" name="name" />
    <input type="submit" class="btn btn-primary" value="New Tag"/>
</form>


<h3>Options</h3>
<table>
    @foreach(var option in Model.Group.GroupOptions)
    {
        <tr>
            <td>@option.Name</td>
            <td><a class="btn btn-secondary" asp-page="/Edit/Option" asp-route-id="@option.Id">Edit</a></td>
            <td>
                <form asp-page-handler="DeleteOption" method="post">
                    <input type="hidden" name="id" value="@option.Id"/>
                    <button class="btn btn-secondary" onclick="return confirm('Are you sure want to delete tag @option.Name?')">Delete</button>
                </form>              
            </td>
        </tr>
    }
</table>
<a class="btn btn-primary" asp-page="/Edit/Option" asp-route-groupId="@Model.Group.Id">New Option</a>

ResumeCoverLetterCreator/Pages/Edit/Index.cshtml
@page
@model ResumeCoverLetterCreator.Pages.Edit.IndexModel
@{
    ViewBag.Title = "Edit Tag Groups";
}
<h1>Tag Groups</h1>
<table>
    @foreach (var group in Model.TagGroups)
    {
        <tr>
            <td>@group.Name</td>
            <td><a class="btn btn-secondary" asp-page="/Edit/Group" asp-route-id="@group.Id">Edit</a></td>
            <td>
                <form asp-page-handler="DeleteGroup" method="post">
                    <input type="hidden" name="id" value="@group.Id"/>
                    <button class="btn btn-secondary" onclick="return confirm('Are you sure want to delete group @group.Name')">Delete</button>
                </form>               
            </td>
        </tr>
    }
</table>
<div class="text-center">
    <form asp-page-handler="AddGroup" method="post">
        <label>Group Name:</label>
        <input name="groupName" type="text" />
        <input type="submit" class="btn btn-primary" value="Add Group" />
    </form>
</div>

ResumeCoverLetterCreator/Pages/Edit/Option.cshtml
@page "{id:int?}"
@model ResumeCoverLetterCreator.Pages.Edit.OptionModel
@{
    ViewBag.Title = Model.Option.Id > 0 ? "Edit Option" : "New Option";
}
<h1>Option</h1>
<label>Group: @Model.Option.TagGroup.Name</label>

<form asp-page-handler="Save" id="option-form" method="post">
    <input type="hidden" name="id" value="@Model.Option.Id" />
    <input type="hidden" name="groupId" value="@Model.Option.TagGroup.Id" />
    <label>Name:</label>
    <input type="text" name="name" value="@Model.Option.Name" /> 

    <h3>Tags Implementations</h3>
    <table>
        @foreach (var tag in @Model.Option.TagGroup.DocumentTags.Where(t => t.TagContent.Any()))
        {
            <tr>           
                <td>
                    @tag.TagName
                </td>
                <td>
                    <select name="tagImplementations[@tag.Id]">
                        @foreach(var implementation in tag.TagContent)
                        {
                            <!option value="@implementation.Id" @(Model.Option.TagContent.Any(c => c.DocumentTag.Id == tag.Id && c.Id == implementation.Id) ? "selected" : "")>@implementation.Content</!option>
                        }
                    </select>
                </td>
            </tr>
        }
    </table>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Save" onclick="return confirm('Save Changes?')" />
    </div>
</form>

ResumeCoverLetterCreator/Pages/Edit/Tag.cshtml
@page "{id:int}"
@model ResumeCoverLetterCreator.Pages.Edit.TagModel
@{
    ViewBag.Title = "Edit Tag";
}
<h1>Tag</h1>
<form  asp-page-handler="ChangeName" method="post">
    <input type="hidden" name="id" value="@Model.Tag.Id" />
    <label>Name:</label>
    <input type="text" name="name" value="@Model.Tag.TagName"/>
    <input class="btn btn-primary" type="submit" value="Save"/>
</form>
<h3>Tag Implementations</h3>
<div id="tagImplementations">
    
    <table>
        @foreach (var implementation in Model.Tag.TagContent)
        {
            <tr>           
                <td colspan="2">
                    <form asp-page-handler="ChangeContent" method="post">
                        <input type="hidden" name="id" value="@implementation.Id" />
                        <input type="text" name="content" value="@implementation.Content" />
                        <input type="submit" value="Save" class="btn btn-secondary" onclick="return confirm('Are you sure want to change tag implementation?')" />
                    </form>                    
                </td>
                <td>
                    <form asp-page-handler="DeleteContent" method="post">
                        <input type="hidden"  name="id" value="@implementation.Id" />
                        <input type="submit"  value="Delete" class="btn btn-secondary" onclick="return confirm('Are you sure want to delete tag implementation?')" />
                    </form>
                </td>
            </tr>      
        }
    </table>   
</div>
<form asp-page-handler="AddContent" method="post">
    <input type="hidden" name="tagId" value="@Model.Tag.Id" />
    <input type="text" name="content" />
    <input type="submit" value="New Implementation" class="btn btn-primary" />
</form>